# Generated by Django 3.2 on 2022-05-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentlineitem',
            old_name='deposit',
            new_name='car_price',
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
