# Generated by Django 3.2 on 2022-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymentlineitem_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='car_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
