# Generated by Django 3.2 on 2022-05-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('payment', '0005_alter_payment_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='profiles.userprofile'),
        ),
    ]
