# Generated by Django 3.2 on 2022-05-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('payment', '0006_payment_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='car_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bid', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car', to='auctions.car'),
        ),
        migrations.DeleteModel(
            name='PaymentLineItem',
        ),
    ]
